# Plugins
gems:
- jekyll-sitemap

safe: false

sass:
  sass_dir: _sass
  style: compressed

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Trà Đá Hacking"
id: "05"
archive: false
status: "Trang web đang xây dựnvui lòng quay lại sau"
#status: ""
email: "trada@vnsecurity.net"
description: "Trà Đá Hacking"
baseurl: ""
url: "http://event.tradahacking.vn/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-78792563-1"
googleAnalyticsSiteUrl: "trada.vnsecurity.net"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "VNSecurity"
organizerAlternateName: "VNSecurity"
organizerDescription: "VNSecurity nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời nhất tại Việt Nam."
organizerEmail: "trada@vnsecurity.net"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.vnsecurity.net/"

# Head
metaKeywords: "vnsec, vnsecurity, tradahacking"
twitterAccount: "@vnsec"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/tradab041.png"

# Documents
c4pUrl: &c4pUrl "http://goo.gl/HTrG3I" #goo.gl/3SkuEZ
c4sponsorsUrl: "mailto:trada@vnsecurity.net?Subject=Sponsor"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Trang Chủ"}
 - {permalink: "/schedule/", text: "Chương trình"}
 - {permalink: "/team/", text: "Ban tổ chức"}
 - {permalink: "/archives.html", text: "Thư viện lưu trữ"}
bottomNavigationLinks:
 - {link: *c4pUrl, text: "Trở thành diễn giả"}
rightNavigationButtons:
 - {link: *c4pUrl, text: "Trở thành diễn giả"}

# Hero Block
heroImage: "tradab04-bg.png"
heroTitle: "Trà Đá Hacking"
eventDate: "26 Tháng 9, 2017"
typeoutTextValues: '"  13/05", "Flemington Tower - Tầng 3 - 182 Lê Đại Hành, Phường 15, Quận 11, Hồ Chí Minh"'
typeoutFallback: ""
heroButtons:
 - {link: *c4pUrl, text: "Trở thành diễn giả"}
 - {permalink: "https://ticketbox.vn/event/tra-da-hacking-04-65154/40896", text: "Đăng ký"}

# About Block
aboutTitle: "Về Trà Đá Hacking"
aboutBlock:
 - {title: "Tại sao là “Trà đá hacking”?", image: "hacked.png", text: "Trong thời đại mà nhà nhà bị hack, người người bị backdoor, vạn vật bị root, xu hướng Internet of Things ở Việt Nam đã, đang và sẽ phơi nhiễm thành Botnet of Things. Sự xuất hiện của “Trà đá hacking” trong bối cảnh hiện nay được ví như ly trà thanh nhiệt giải toả cơn khát giúp thúc đẩy phong trào học tập và nghiên cứu An Ninh thông tin chuyên sâu, cũng như tạo ra một không gian trao đổi và nghiên cứu cho cộng đồng nói chung và các bạn trẻ yêu thích hacking/security ở Việt Nam nói riêng." }
 - {title: "Ai đứng ra tổ chức?", image: "vnsec.png", text: "Được tổ chức bởi VNSecurity, nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "người tham dự", detail: ""}
 - {count: "4", specialCharacter: "", info: "giờ", detail: ""}
 - {count: "8", specialCharacter: "+", info: "diễn giả", detail: ""}
 - {count: "7", specialCharacter: "", info: "chủ đề", detail: ""}

# Latest News Block
latestNewsTitle: "Tin mới"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Diễn giả nổi bật"
rockstarSpeakersButtonText: "Xem tất cả các diễn giả"

# Location Block
locationBlockTitle: "Địa điểm"
eventLocationName: "HCM"
eventLocationLink: ""
eventStreetAddress: "Flemington Tower - Tầng 3 - 182 Lê Đại Hành, Phường 15, Quận 11, Hồ Chí Minh"
eventAddressLocality: "Đà Nẵng"
eventAddressLocalityRegion: "DN"
eventPostalCode: "70000"
eventAddressCountry: "Việt nam"
eventStartTime: "2017-09-22T13:30"
eventDoorTime: "13:00"
eventEndTime: "2017-09-22T18:00"
eventPlaceCoordinates: "16.0612153,108.2247871,17"
mapCenterCoordinates: "16.0612153,108.2247871,17"
mapMobileCenterCoordinates: "16.0612153,108.2247871,17"

# Venue Block
venueBlockTitle: "Nơi tổ chức"
venueBigImage: "venue_2.jpg"
venueSmallImage1: "venue_3.jpg"
venueTitle: "Flemington Tower - Tầng 3 - 182 Lê Đại Hành, Phường 15, Quận 11, Hồ Chí Minh"
venueFeatures: [""]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "tradahacking"
twitterFeed: "http://"

# Partners Block
organizersTitle: "Ban tổ chức"
partnersTitle: "Nhà tài trợ"
partnersC4sponsorsButton: "Trở thành nhà tài trợ"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Đăng ký để nhận thông tin mới"
subscribeAction: "http://www.vnsecurity.net"
subscribeInfo: ""

# Tickets Block
ticketsTitle: "Phí tham dự"
ticketsInfo: "Trà Đá Hacking là sự kiện phi lợi nhuận. Chúng tôi chỉ thu phí tượng trưng để hỗ trợ 'một phần' chi phí tổ chức sự kiện và địa điểm. BTC cũng tặng vé miễn phí cho một số lượng lớn các sinh viên đam mê bảo mật. Tất cả các tiền tài trợ sau khi trừ chi phí nếu còn dư sẽ được sử dụng để tổ chức các kỳ Trà Đá Hacking sau.<br />"
ticketsOffers:
 -
  name: "Vé tham dự"
  price: "99000 "
  priceCurrency: "VND"
  ticketsNumber: "200"
  ribbon: "0%"
  buyButtonLink: "https://ticketbox.vn/event/tra-da-hacking-04-65154/40896"
  buyButtonText: "Đăng ký tham dự"
  ticketContentList: [""]
  validThrough: "2017-05-10T00:00"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=vnsec", icon: "twitter"}
 - {link: "https://facebook.com/vnsec", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.vnsecurity.net", text: "VNSecurity"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:trada@vnsecurity.net", text: "trada@vnsecurity.net"}


# Blog
blogTitle: "Tin tức"
blogCommentsEnabled: false
discusShortName: "tradahacking"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Về chúng tôi"
aboutUs: "VNSecurity là nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet."


