# Plugins
gems:
- jekyll-sitemap

safe: false

sass:
  sass_dir: _sass
  style: compressed

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Trà Đá Hacking"
email: "tradahacking@vnsecurity.net"
description: "Trà Đá Hacking"
baseurl: ""
url: "http://tradahacking.vnsecurity.net"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "tradahacking.vnsecurity.net"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "VNSecurity"
organizerAlternateName: "VNSecurity"
organizerDescription: "VNSECURITY nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời nhất tại Việt Nam."
organizerEmail: "tradahacking@vnsecurity.net"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.vnsecurity.net/"

# Head
metaKeywords: "vnsec, vnsecurity, tradahacking"
twitterAccount: "@vnsec"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://goo.gl/forms/zYmm6CdauKQcQpC72"
c4sponsorsUrl: "/assets/trada.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Trang Chủ"}
 - {permalink: "/schedule/", text: "Chương trình"}
 - {permalink: "/team/", text: "Ban tổ chức"}
bottomNavigationLinks:
 - {link: c4pUrl, text: "Trở thành diễn giả"}
rightNavigationButtons:
 - {link: c4pUrl, text: "Trở thành diễn giả"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Trà Đá Hacking"
eventDate: "11 Tháng 6, 2016"
typeoutTextValues: '"  11/06", "  Saigon"'
typeoutFallback: ""
heroButtons:
 - {link: c4pUrl, text: "Trở thành diễn giả"}
 - {permalink: "/#tickets", text: "Đăng ký"}

# About Block
aboutTitle: "Về Trà Đá Hacking"
aboutBlock:
 - {title: "Tại sao là “Trà đá hacking”?", image: "hacked.png", text: "Sự xuất hiện của buổi offline “Trà đá hacking” do nhóm vnsecurity tổ chức trong bối cảnh hiện nay được ví như ly trà thanh nhiệt giải toả cơn khát kéo dài về nhu cầu học tập/ trao đổi/ nâng cao kiến thức cho cộng đồng nói chung và các bạn trẻ yêu thích hacking/security ở Việt Nam nói riêng. Trong thời đại mà nhà nhà bị hack, người người bị backdoor, vạn vật bị root, xu hướng Internet of Things ở Việt Nam đã, đang và sẽ phơi nhiễm thành Botnet of Things" }
 - {title: "Ai đứng ra tổ chức?", image: "vnsec.png", text: "Được tổ chức bởi Vnsecurity, nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "người tham dự", detail: ""}
 - {count: "4", specialCharacter: "+", info: "giờ", detail: ""}
 - {count: "4", specialCharacter: "+", info: "diễn giả", detail: ""}
 - {count: "4", specialCharacter: "", info: "chủ đề", detail: ""}

# Latest News Block
latestNewsTitle: "Tin mới"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Diễn giả nổi bật"
rockstarSpeakersButtonText: "Xem tất cả các diễn giả"

# Location Block
locationBlockTitle: "Địa điểm"
eventLocationName: "Sài Gòn"
eventLocationLink: "http://xxx/"
eventStreetAddress: "182 Lê Đại Hành, Quận 11"
eventAddressLocality: "Hồ Chí Minh"
eventAddressLocalityRegion: "SG"
eventPostalCode: "70000"
eventAddressCountry: "Việt nam"
eventStartTime: "2016-06-11T09:00"
eventDoorTime: "09:00"
eventEndTime: "2016-06-11T12:00"
eventPlaceCoordinates: "10.764219, 106.656323"
mapCenterCoordinates: "10.764219, 106.656323"
mapMobileCenterCoordinates: "10.764219, 106.656323"

# Venue Block
venueBlockTitle: "Nơi tổ chức"
venueBigImage: "venue_2.jpg"
venueSmallImage1: "venue_3.jpg"
venueTitle: "182 Lê Đại Hành, Quận 11, TP Hồ Chí Minh"
venueFeatures: [""]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "tradahacking"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Ban tổ chức"
partnersTitle: "Nhà tài trợ"
partnersC4sponsorsButton: "Trở thành nhà tài trợ"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Đăng ký để nhận thông tin mới"
subscribeAction: "http://www.vnsecurity.net"
subscribeInfo: "Số lượng vé có hạn. Đăng ký sẽ kết thúc vào 12 giờ trưa 10/06/2016!"

# Tickets Block
ticketsTitle: "Phí tham dự"
ticketsInfo: "Trà Đá Hacking chỉ thu phí 50.000 VNĐ cho việc thuê địa điểm tổ chức."
ticketsOffers:
 -
  name: "Phí tham dự"
  price: "50.000 "
  priceCurrency: "VND"
  ticketsNumber: "100"
  ribbon: "0%"
  buyButtonLink: "http://www.vnsecurity.net"
  buyButtonText: "Đăng ký"
  ticketContentList: [""]
  validThrough: "2016-06-11"


# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=vnsec", icon: "twitter"}
 - {link: "https://facebook.com/vnsec", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.vnsecurity.net", text: "VNSecurity"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:tradahacking@vnsecurity.net", text: "tradahacking@vnsecurity.net"}


# Blog
blogTitle: "Tin tức"
blogCommentsEnabled: false
discusShortName: "tradahacking"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Về chúng tôi"
aboutUs: "VNSecurity là nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet."


