# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Trà Đá Hacking"
email: "rd@vnsecurity.net"
description: "Trà Đá Hacking"
baseurl: "/tradahacking"
url: "http://redragonvn.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "redragonvn.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "VNSecurity"
organizerAlternateName: "VNSecurity"
organizerDescription: "VNSECURITY nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời nhất tại Việt Nam."
organizerEmail: "rd@vnsecurity.net"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.vnsecurity.net/"

# Head
metaKeywords: "vnsec, vnsecurity, tradahacking"
twitterAccount: "@vnsec"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://www.vnsecurity.net/"
c4sponsorsUrl: "/assets/trada.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Trang Chủ"}
 - {permalink: "/news/", text: "Tin tức"}
 - {permalink: "/schedule/", text: "Chương trình"}
 - {permalink: "/speakers/", text: "Diễn giả"}
 - {permalink: "/team/", text: "Ban tổ chức"}
bottomNavigationLinks:
 - {link: "http://www.vnsecurity.net/", text: "Trở thành diễn giả"}
rightNavigationButtons:
 - {link: "http://www.vnsecurity.net/", text: "Trở thành diễn giả"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Trà Đá Hacking"
eventDate: "11 Tháng 6, 2016 "
typeoutTextValues: '"", " #1 2016"'
typeoutFallback: " #1 2016"
heroButtons:
 - {link: "http://www.vnsecurity.net/", text: "Trở thành diễn giả"}
 - {permalink: "/#tickets", text: "Đăng ký"}

# About Block
aboutTitle: "Về Trà Đá Hacking"
aboutBlock:
 - {title: "Tại sao là “Trà đá hacking”?", image: "conference.jpg", text: "Sự xuất hiện của buổi offline “Trà đá hacking” do nhóm vnsecurity tổ chức trong bối cảnh hiện nay được ví như ly trà thanh nhiệt giải toả cơn khát kéo dài về nhu cầu học tập/ trao đổi/ nâng cao kiến thức cho cộng đồng nói chung và các bạn trẻ yêu thích hacking/security ở Việt Nam nói riêng. Trong thời đại mà nhà nhà bị hacked, người người bị backdoored, vạn vật bị root, xu hướng Internet of Things ở Việt Nam đã, đang và sẽ phơi nhiễm thành Botnet of Things" }
 - {title: "Ai đứng ra tổ chức?", image: "workshop.jpg", text: "Được tổ chức bởi Vnsecurity, nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50-100", specialCharacter: "+", info: "người tham dự", detail: "tại Sài Gòn"}
 - {count: "4", specialCharacter: "+", info: "giờ", detail: "trà chanh chém gió về an toàn thông tin"}
 - {count: "4", specialCharacter: "+", info: "diễn giả", detail: ""}
 - {count: "4", specialCharacter: "", info: "chủ đề", detail: ""}

# Latest News Block
latestNewsTitle: "Tin mới"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Diễn giả nổi bật"
rockstarSpeakersButtonText: "Xem tất cả các diễn giả"

# Location Block
locationBlockTitle: "Địa điểm"
eventLocationName: "Chưa biết ở đâu"
eventLocationLink: "http://xxx/"
eventStreetAddress: "182 Lê Đại Hành, Quận 11"
eventAddressLocality: "Hồ Chí Minh"
eventAddressLocalityRegion: "SG"
eventPostalCode: "70000"
eventAddressCountry: "Việt nam"
eventStartTime: "2016-06-11T09:00"
eventDoorTime: "09:00"
eventEndTime: "2016-06-11T12:00"
eventPlaceCoordinates: "10.7516793,106.6097252"
mapCenterCoordinates: "10.7516793,106.6097252"
mapMobileCenterCoordinates: "10.7516793,106.6097252"

# Venue Block
venueBlockTitle: "Nơi tổ chức"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueTitle: "Chưa biết"
venueFeatures: ["LCD Projector", ""]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "tradahacking"
twitterFeed: "http://twitterfeedlink"

# Partners Block
organizersTitle: "Ban tổ chức"
partnersTitle: "Nhà tài trợ"
partnersC4sponsorsButton: "Trở thành nhà tài trợ"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Đăng ký để nhận thông tin mới"
subscribeAction: "http://emailform"
subscribeInfo: "Số lượng vé có hạn. Đăng ký sẽ kết thúc vào 12 giờ trưa 10/06/2016!"

# Tickets Block
ticketsTitle: "Phí tham dự"
ticketsInfo: "Trà Đá Hacking chỉ thu phí 50.000 VNĐ cho việc thuê địa điểm tổ chức."
ticketsOffers:
 -
  name: "Phí tham dự"
  price: "50.000 "
  priceCurrency: "VND"
  ticketsNumber: "200"
  ribbon: "0%"
  buyButtonLink: "http://ticketbox"
  buyButtonText: "Đăng ký"
  ticketContentList: [""]

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Về chúng tôi"
aboutUs: "VNSecurity là nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet."

directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
