# Plugins 
gems:
- jekyll-sitemap

safe: false

sass:
  sass_dir: _sass
  style: compressed

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Trà Đá Hacking"
id: ""
archive: false 
#status: "Trang web đang xây dựng vui lòng quay lại sau"
status: ""
email: "trada@vnsecurity.net"
description: "Trà Đá Hacking"
baseurl: ""
url: "http://event.tradahacking.vn/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-78792563-1"
googleAnalyticsSiteUrl: "trada.vnsecurity.net"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "VNSecurity"
organizerAlternateName: "VNSecurity"
organizerDescription: "VNSecurity nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời nhất tại Việt Nam!"
organizerEmail: "trada@vnsecurity.net"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.vnsecurity.net/"

# Head
metaKeywords: "vnsec, vnsecurity, tradahacking"
twitterAccount: "@vnsec"
socialImageSrcGooglePlus: "/img/seo/trada7-seo.png"
socialImageSrcTwitter: "/img/seo/trada7-seo.png"
socialImageSrcFacebook: "/img/seo/trada7-seo.png"

# Documents
c4pUrl: &c4pUrl "https://goo.gl/iq5VEq" #"https://goo.gl/aHu6rK" #goo.gl/3SkuEZ
c4sponsorsUrl: "mailto:trada@vnsecurity.net?Subject=Tradahacking7-Sponsor"
c4tUrl: &c4tUrl "https://goo.gl/xjnbqA"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Trang Chủ"}
 - {permalink: "/schedule/", text: "Chương trình"}
 - {permalink: "/team/", text: "Ban tổ chức"}
 - {permalink: "/archives.html", text: "Thư viện lưu trữ"}
bottomNavigationLinks:
 - {link: *c4pUrl, text: "Trở thành diễn giả"}
 - {link: *c4tUrl, text: "Trở thành giảng viên"}
rightNavigationButtons:
 - {link: *c4pUrl, text: "Trở thành diễn giả"}
 - {link: *c4tUrl, text: "Trở thành giảng viên"}

# Hero Block
heroImage: "trada7-final.png"
heroTitle: ""
eventDate: ""
typeoutTextValues: '" ", ""'
typeoutFallback: ""
heroButtons:
 - {link: *c4pUrl, text: "Trở thành diễn giả"}
 - {permalink: "https://ticketbox.vn/", text: "Đăng ký"}
 - {link: *c4tUrl, text: "Trở thành giảng viên"}

# About Block
aboutTitle: "Về Trà Đá Hacking"
aboutBlock:
 - {title: "Tại sao là “Trà đá hacking”?", image: "hacked.png", text: "Trong thời đại mà nhà nhà bị hack, người người bị backdoor, vạn vật bị root, xu hướng Internet of Things ở Việt Nam đã, đang và sẽ phơi nhiễm thành Botnet of Things. Sự xuất hiện của “Trà đá hacking” trong bối cảnh hiện nay được ví như ly trà thanh nhiệt giải toả cơn khát giúp thúc đẩy phong trào học tập và nghiên cứu An Ninh thông tin chuyên sâu, cũng như tạo ra một không gian trao đổi và nghiên cứu cho cộng đồng nói chung và các bạn trẻ yêu thích hacking/security ở Việt Nam nói riêng." }
 - {title: "Ai đứng ra tổ chức?", image: "vnsec.png", text: "Được tổ chức bởi VNSecurity, nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet." }
 - {title: "Trà đá hacking workshop", image: "workshop.png", text: "Được tổ chức bởi VNSecurity, nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "người tham dự", detail: ""}
 - {count: "4", specialCharacter: "", info: "giờ", detail: ""}
 - {count: "8", specialCharacter: "+", info: "diễn giả", detail: ""}
 - {count: "7", specialCharacter: "", info: "chủ đề", detail: ""}

# Latest News Block
latestNewsTitle: "Tin mới"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Diễn giả nổi bật"
rockstarSpeakersButtonText: "Xem tất cả các diễn giả"

# Rockstar Trainers Block
rockstarTrainersImage: "rockstar-speakers.jpg"
rockstarTrainersCount: 4
rockstarTrainersTitle: "Giảng viên nổi bật"
rockstarTrainersButtonText: "Xem tất cả các giảng viên"

# Location Block
locationBlockTitle: "Địa điểm"
eventLocationName: "Toà nhà FPT Tân Thuận, HCMC"
eventLocationLink: "http://www.vnsecurity.net/"
eventStreetAddress: "Lô L29B-31B—33B, đường số 8, KCX Tân Thuận, P. Tân Thuận Đông"
eventAddressLocality: "Quận 7"
eventAddressLocalityRegion: "HCMC"
eventPostalCode: "700000"
eventAddressCountry: "Việt nam"
eventStartTime: "Aug 26, 2018 08:30 GMT+7"
eventDoorTime: "08:00"
eventEndTime: "Aug 26, 2018 18:00 GMT+7"
eventPlaceCoordinates: "10.760682,106.7356331"
mapCenterCoordinates: "10.760682,106.7356331"
mapMobileCenterCoordinates: "10.760682,106.7356331"

# Venue Block
venueBlockTitle: "Nơi tổ chức"
venueBigImage: "venue_2.jpg"
venueSmallImage1: "venue_3.jpg"
venueTitle: "Ho Chi Minh"
venueFeatures: [""]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "TraDaHacking#7?"
twitterHashTag: "tradahacking"
twitterFeed: "http://"

# Partners Block
organizersTitle: "Ban tổ chức"
partnersTitle: "Nhà tài trợ"
partnersC4sponsorsButton: "Trở thành nhà tài trợ"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Đăng ký để nhận thông tin mới"
subscribeAction: "http://www.vnsecurity.net"
subscribeInfo: ""

# Tickets Block
ticketsTitle: "Phí tham dự"
ticketsInfo: "Trà Đá Hacking là sự kiện phi lợi nhuận. Chúng tôi chỉ thu phí tượng trưng để hỗ trợ 'một phần' chi phí tổ chức sự kiện và địa điểm. BTC cũng tặng vé miễn phí cho một số lượng lớn các sinh viên đam mê bảo mật. Tất cả các tiền tài trợ sau khi trừ chi phí nếu còn dư sẽ được sử dụng để tổ chức các kỳ Trà Đá Hacking sau.<br />"
ticketsOffers:
 -
  name: "Vé đăng ký sớm"
  price: "99.000"
  priceCurrency: "VND"
  ticketsNumber: "200"
  ribbon: "-66.6%"
  buyButtonLink: "https://ticketbox.vn/"
  buyButtonText: "Mua ngay"
  ticketContentList: [""]
  validFrom: "Jul 17, 2018 12:00 GMT+7"
  validThrough: "Aug 26, 2018 12:00 GMT+7"
 -
  name: "Vé thường"
  price: "149.000"
  priceCurrency: "VND"
  ticketsNumber: "150"
  ribbon: ""
  featured: true
  buyButtonLink: "https://ticketbox.vn/"
  buyButtonText: "Mua ngay"
  ticketContentList: []
  validFrom: "Aug 15, 2018 12:00 GMT+7"
  validThrough: "Aug 26, 2018 13:30 GMT+7"
  disabled: true
# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=vnsec", icon: "twitter"}
 - {link: "https://www.facebook.com/tradahackingvn/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.vnsecurity.net", text: "VNSecurity"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:trada@vnsecurity.net", text: "trada@vnsecurity.net"}


# Blog
blogTitle: "Tin tức"
blogCommentsEnabled: false
discusShortName: "tradahacking"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Về chúng tôi"
aboutUs: "VNSecurity là nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet."


