# Plugins
gems:
- jekyll-sitemap

safe: false

sass:
  sass_dir: _sass
  style: compressed

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Trà Đá Hacking"
id: "02"
archive: false
#status: "Trang web đang xây dựnvui lòng quay lại sau"
status: ""
email: "trada@vnsecurity.net"
description: "Trà Đá Hacking"
baseurl: ""
url: "http://trada.vnsecurity.net/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-78792563-1"
googleAnalyticsSiteUrl: "trada.vnsecurity.net"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "VNSecurity"
organizerAlternateName: "VNSecurity"
organizerDescription: "VNSecurity nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời nhất tại Việt Nam."
organizerEmail: "trada@vnsecurity.net"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.vnsecurity.net/"

# Head
metaKeywords: "vnsec, vnsecurity, tradahacking"
twitterAccount: "@vnsec"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook0.png"

# Documents
c4pUrl: &c4pUrl "http://goo.gl/forms/zYmm6CdauKQcQpC72"
c4sponsorsUrl: "mailto:trada@vnsecurity.net?Subject=Sponsor"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Trang Chủ"}
 - {permalink: "/schedule/", text: "Chương trình"}
 - {permalink: "/team/", text: "Ban tổ chức"}
 - {permalink: "/archives.html", text: "Thư viện lưu trữ"}
bottomNavigationLinks:
 - {link: *c4pUrl, text: "Trở thành diễn giả"}
rightNavigationButtons:
 - {link: *c4pUrl, text: "Trở thành diễn giả"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Trà Đá Hacking"
eventDate: "16 Tháng 9, 2016"
typeoutTextValues: '"  16/09", "  Hanoi"'
typeoutFallback: ""
heroButtons:
 - {link: *c4pUrl, text: "Trở thành diễn giả"}
 - {permalink: "/#tickets", text: "Đăng ký"}

# About Block
aboutTitle: "Về Trà Đá Hacking"
aboutBlock:
 - {title: "Tại sao là “Trà đá hacking”?", image: "hacked.png", text: "Sự xuất hiện của buổi offline “Trà đá hacking” do nhóm VNSecurity tổ chức trong bối cảnh hiện nay được ví như ly trà thanh nhiệt giải toả cơn khát kéo dài về nhu cầu học tập/ trao đổi/ nâng cao kiến thức cho cộng đồng nói chung và các bạn trẻ yêu thích hacking/security ở Việt Nam nói riêng. Trong thời đại mà nhà nhà bị hack, người người bị backdoor, vạn vật bị root, xu hướng Internet of Things ở Việt Nam đã, đang và sẽ phơi nhiễm thành Botnet of Things" }
 - {title: "Ai đứng ra tổ chức?", image: "vnsec.png", text: "Được tổ chức bởi VNSecurity, nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "người tham dự", detail: ""}
 - {count: "4", specialCharacter: "", info: "giờ", detail: ""}
 - {count: "8", specialCharacter: "+", info: "diễn giả", detail: ""}
 - {count: "7", specialCharacter: "", info: "chủ đề", detail: ""}

# Latest News Block
latestNewsTitle: "Tin mới"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Diễn giả nổi bật"
rockstarSpeakersButtonText: "Xem tất cả các diễn giả"

# Location Block
locationBlockTitle: "Địa điểm"
eventLocationName: "Hà Nội"
eventLocationLink: ""
eventStreetAddress: ""
eventAddressLocality: ""
eventAddressLocalityRegion: ""
eventPostalCode: "70000"
eventAddressCountry: "Việt nam"
eventStartTime: "2016-09-16T13:30"
eventDoorTime: "13:30"
eventEndTime: "2016-09-16T18:00"
eventPlaceCoordinates: "21.036392, 105.834989"
mapCenterCoordinates: "21.036392, 105.834989"
mapMobileCenterCoordinates: "21.036392, 105.834989"

# Venue Block
venueBlockTitle: "Nơi tổ chức"
venueBigImage: "venue_2.jpg"
venueSmallImage1: "venue_3.jpg"
venueTitle: "Sẽ thông báo sau"
venueFeatures: [""]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "tradahacking"
twitterFeed: "http://"

# Partners Block
organizersTitle: "Ban tổ chức"
partnersTitle: "Nhà tài trợ"
partnersC4sponsorsButton: "Trở thành nhà tài trợ"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Đăng ký để nhận thông tin mới"
subscribeAction: "http://www.vnsecurity.net"
subscribeInfo: ""

# Tickets Block
ticketsTitle: "Phí tham dự"
ticketsInfo: "Trà Đá Hacking là sự kiện phi lợi nhuận. Chúng tôi chỉ thu phí tượng trưng để hỗ trợ 'một phần' chi phí tổ chức sự kiện và địa điểm. BTC cũng tặng vé miễn phí cho một số lượng lớn các sinh viên đam mê bảo mật. Tất cả các tiền tài trợ sau khi trừ chi phí nếu còn dư sẽ được sử dụng để tổ chức các kỳ Trà Đá Hacking sau.<br />"
ticketsOffers:
 -
  name: "Vé mua trước 04/09"
  price: "80.000 "
  priceCurrency: "VND"
  ticketsNumber: "150"
  ribbon: "0%"
  buyButtonLink: "https://ticketbox.vn/event/tradahacking-62467/37074"
  buyButtonText: "Đăng ký tham dự"
  ticketContentList: [""]
  validThrough: "2016-09-04T00:00"
 -
  name: "Vé mua sau 04/09"
  price: "120.000 "
  priceCurrency: "VND"
  ticketsNumber: "50"
  ribbon: "0%"
  buyButtonLink: "https://ticketbox.vn/event/tradahacking-62467/37074"
  buyButtonText: "Đăng ký tham dự"
  ticketContentList: [""]
  validFrom: "2016-09-04T00:00"
  validThrough: "2016-09-16T08:00"


# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=vnsec", icon: "twitter"}
 - {link: "https://facebook.com/vnsec", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.vnsecurity.net", text: "VNSecurity"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:trada@vnsecurity.net", text: "trada@vnsecurity.net"}


# Blog
blogTitle: "Tin tức"
blogCommentsEnabled: false
discusShortName: "tradahacking"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Về chúng tôi"
aboutUs: "VNSecurity là nhóm nghiên cứu chuyên sâu về bảo mật máy tính lâu đời tại Việt Nam. Nhiều thành viên trong nhóm có những nghiên cứu và sản phẩm được cộng đồng trên thế giới đánh giá cao. Số khác trong đó thường xuyên công bố các lỗ hổng bảo mật nghiêm trọng trong các giao thức xương sống và phần mềm phổ biến trên internet."


